Repository ultralytics/mobileclip, pull requests merged in 2025-04, with the labels that each got.

#2 Create format.yml
  .github/workflows/format.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  eval/zeroshot_imagenet.py
  hf_dataset_example.py
  ios_app/MobileCLIPExplore/Assets.xcassets/AccentColor.colorset/Contents.json
  ios_app/MobileCLIPExplore/Assets.xcassets/AddClassName.colorset/Contents.json
  ios_app/MobileCLIPExplore/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios_app/MobileCLIPExplore/Assets.xcassets/Contents.json
  ios_app/MobileCLIPExplore/Assets.xcassets/Preset.colorset/Contents.json
  ios_app/MobileCLIPExplore/Assets.xcassets/PresetDisabled.colorset/Contents.json
  ios_app/MobileCLIPExplore/Assets.xcassets/PromptEditor.colorset/Contents.json
  ios_app/MobileCLIPExplore/Assets.xcassets/PromptEditorBackground.colorset/Contents.json
  ios_app/MobileCLIPExplore/Models/README.md
  ios_app/MobileCLIPExplore/Preview Content/Preview Assets.xcassets/Contents.json
  ios_app/MobileCLIPExplore/Resources/clip-vocab.json
  ios_app/README.md
  mobileclip/__init__.py
  mobileclip/clip.py
  mobileclip/configs/mobileclip_b.json
  mobileclip/configs/mobileclip_s0.json
  mobileclip/configs/mobileclip_s1.json
  mobileclip/configs/mobileclip_s2.json
  mobileclip/image_encoder.py
  mobileclip/logger.py
  mobileclip/models/mci.py
  mobileclip/models/vit.py
  mobileclip/modules/common/mobileone.py
  mobileclip/modules/common/transformer.py
  mobileclip/modules/image/image_projection.py
  mobileclip/modules/image/replknet.py
  mobileclip/modules/text/repmixer.py
  mobileclip/modules/text/tokenizer.py
  mobileclip/text_encoder.py
  setup.py
  training/README.md
  training/configs/datacompdr12m.json
  training/configs/datacompdr1b.json
  training/dr/transforms.py
  training/dr/transforms_base.py
Labels: documentation, enhancement

#3 Create ci.yml
  .github/workflows/ci.yml
  requirements.txt
Labels: dependencies, enhancement

#4 Update READMEs
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#5 Create `pyproject.toml` file
  pyproject.toml
  requirements.txt
  setup.py
Labels: dependencies, enhancement

#6 Update pyproject.toml
  pyproject.toml
Labels: dependencies, enhancement
